
name: Link Checker

on: push
# on:
#   repository_dispatch:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 * * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: --verbose --no-progress --exclude-all-private **/*.md **/*.html --base-url https://napari.org --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
        env:
          GITHUB_TOKEN: ${{secrets.DOCS_GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
